//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute("b378d9cd-2817-4513-a75f-1e91724e3131")]
[assembly: System.Reflection.AssemblyCompanyAttribute("ExchangeRateConsole")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © 2023 Scott Glasgow")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("ExchangeRateConsole")]
[assembly: System.Reflection.AssemblyTitleAttribute("Exchange Rate Console")]
[assembly: System.Reflection.AssemblyVersionAttribute("2.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

