# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Exchange Rate Console .NET 9 Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.gz'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.gz'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.x.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test

      run: dotnet test --no-build --verbosity normal