# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Exchange Rate Console .NET 7 Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.gz'
      - '**.sql'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.gz'
      - '**.sql'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x.x
    - name: Restore dependencies
      run: dotnet restore --runtime linux-x64
    - name: Build
      run: dotnet build --configuration Release --no-restore --framework net7.0
    - name: Test
      run: dotnet test --no-build --verbosity normal
